export const respondentFormFields = [
  {
    name: "name",
    label: "Nama Lengkap",
    type: "text",
    required: true,
    validation: { required: "Nama wajib diisi" },
  },
  {
    name: "dateOfBirth",
    label: "Tanggal Lahir",
    type: "date",
    required: true,
    validation: { required: "Tanggal lahir wajib diisi" },
  },
  {
    name: "age",
    label: "Usia (otomatis)",
    type: "number",
    disabled: true,
  },
  {
    name: "gender",
    label: "Jenis Kelamin",
    type: "select",
    required: true,
    options: ["Laki-laki", "Perempuan"],
    validation: { required: "Jenis kelamin wajib dipilih" },
  },
  {
    name: "phoneNumber",
    label: "Nomor HP",
    type: "tel",
    required: true,
    validation: { required: "Nomor HP wajib diisi" },
  },
  {
    name: "educationLevel",
    label: "Pendidikan Terakhir",
    type: "select",
    required: true,
    options: ["SD", "SMP", "SMA", "S1"],
    validation: { required: "Pendidikan wajib dipilih" },
  },
  {
    name: "schoolName",
    label: "Nama Sekolah / Perguruan Tinggi",
    type: "text",
    required: true,
    validation: { required: "Nama sekolah wajib diisi" },
  },
  {
    name: "livingWith",
    label: "Tinggal Dengan",
    type: "text",
  },
  {
    name: "address",
    label: "Alamat",
    type: "text",
  },
  {
    name: "parentOccupation",
    label: "Pekerjaan Orang Tua",
    type: "text",
  },
  {
    name: "birthOrder",
    label: "Anak Ke-",
    type: "text",
  },
  {
    name: "ethnicity",
    label: "Suku / Etnis",
    type: "text",
  },
];
